@echo off

powershell -command "Get-ChildItem -Path '%LocalAppData%\Discord' -Directory -Filter 'app-*' | Sort-Object { [version]($_.Name -replace 'app-', '') } | Select-Object -SkipLast 1 | ForEach-Object { Remove-Item -Path $_.FullName -Recurse -Force }"
powershell -command "Get-ChildItem -Path '%LocalAppData%\GitHubDesktop' -Directory -Filter 'app-*' | Sort-Object { [version]($_.Name -replace 'app-', '') } | Select-Object -SkipLast 1 | ForEach-Object { Remove-Item -Path $_.FullName -Recurse -Force }"
powershell -command "Get-ChildItem -Path '%LocalAppData%\WeMod' -Directory -Filter 'app-*' | Sort-Object { [version]($_.Name -replace 'app-', '') } | Select-Object -SkipLast 1 | ForEach-Object { Remove-Item -Path $_.FullName -Recurse -Force }"
powershell -command "Get-ChildItem -Path '%LocalAppData%\Postman' -Directory -Filter 'app-*' | Sort-Object { [version]($_.Name -replace 'app-', '') } | Select-Object -SkipLast 1 | ForEach-Object { Remove-Item -Path $_.FullName -Recurse -Force }"
powershell -Command "Get-ChildItem -Path '%LocalAppData%\Roblox\Versions' -Directory | Sort-Object CreationTime | Select-Object -SkipLast 1 | ForEach-Object { Remove-Item -Path $_.FullName -Recurse -Force }"
powershell -command "Remove-Item '%temp%\*' -Recurse -Force -ErrorAction SilentlyContinue"
attrib +h +s "%LocalAppData%\ConnectedDevicesPlatform"
attrib -h -s "%LocalAppData%\IconCache.db"
del "%LocalAppData%\Discord\*.log"
del "%LocalAppData%\GitHubDesktop\*.log"
del "%LocalAppData%\Postman\*.log"
del "%LocalAppData%\IconCache.db"
del "%LocalAppData%\UserProducts.xml"
del "%LocalAppData%\WeMod\*.log"
del "%LocalAppData%\nzxt cam-updater\installer.exe"
del "%LocalAppData%\GameAnalyticsga.sqlite3"
del "%LocalAppData%\updater.log"
del "%LocalAppData%\Roblox\rbx-storage*"
del "%UserProfile%\.VirtualBox\*.log*"
del "%UserProfile%\.node_repl_history"
del "%UserProfile%\Zomboid\*.log"
del "%UserProfile%\Zomboid\logs.zip"
del "%UserProfile%\setup.dat"
del "%UserProfile%\AppData\LocalLow\LocalLog.log" /s /q
del "%UserProfile%\AppData\LocalLow\Player.log" /s /q
del "%UserProfile%\AppData\LocalLow\Player-prev.log" /s /q
del "%UserProfile%\AppData\LocalLow\output_log.txt" /s /q
del "%UserProfile%\AppData\LocalLow\output_log.txt.last" /s /q
for /d %%G in ("%SystemDrive%\Program Files\chrome_url_fetcher_*") do rd /s /q "%%~G"
rd /s /q "%AppData%\.1911"
rd /s /q "%AppData%\Code\Cache"
rd /s /q "%AppData%\Code\CachedData"
rd /s /q "%AppData%\Code\Code Cache"
rd /s /q "%AppData%\Code\GPUCache"
rd /s /q "%AppData%\Code\logs"
rd /s /q "%AppData%\DMCache"
rd /s /q "%AppData%\GitHub Desktop\Cache"
rd /s /q "%AppData%\GitHub Desktop\Code Cache"
rd /s /q "%AppData%\GitHub Desktop\GPUCache"
rd /s /q "%AppData%\GitHub Desktop\logs"
rd /s /q "%AppData%\NZXT CAM\Cache"
rd /s /q "%AppData%\NZXT CAM\Code Cache"
rd /s /q "%AppData%\NZXT CAM\GPUCache"
rd /s /q "%AppData%\NZXT CAM\logs"
rd /s /q "%AppData%\arduino-ide\Cache"
rd /s /q "%AppData%\arduino-ide\Code Cache"
rd /s /q "%AppData%\arduino-ide\GPUCache"
rd /s /q "%AppData%\arduino-ide\logs"
rd /s /q "%AppData%\discord\Cache"
rd /s /q "%AppData%\discord\Code Cache"
rd /s /q "%AppData%\discord\GPUCache"
rd /s /q "%AppData%\discord\logs"
rd /s /q "%AppData%\mpv\watch_laters"
rd /s /q "%AppData%\.tlauncher\cache"
rd /s /q "%AppData%\.tlauncher\logs"
rd /s /q "%AppData%\.tlauncher\starter"
rd /s /q "%AppData%\java"
rd /s /q "%AppData%\NVIDIA"
rd /s /q "%AppData%\ow-electron"
rd /s /q "%AppData%\Cognosphere"
rd /s /q "%AppData%\CurseForge\Cache"
rd /s /q "%AppData%\CurseForge\Code Cache"
rd /s /q "%AppData%\CurseForge\GPUCache"
rd /s /q "%AppData%\CurseForge\File System"
rd /s /q "%AppData%\CurseForge\logs"
rd /s /q "%AppData%\WeMod\Code Cache"
rd /s /q "%AppData%\WeMod\games\logs"
rd /s /q "%AppData%\WeMod\games\crash"
rd /s /q "%AppData%\WeMod\App\trainers"
rd /s /q "%AppData%\OpenVPN Connect\log"
rd /s /q "%AppData%\Naughty Dog"
rd /s /q "%AppData%\Maxon"
rd /s /q "%AppData%\utorrent"
rd /s /q "%AppData%\The Sims 4"
rd /s /q "%AppData%\The Witcher 3"
rd /s /q "%AppData%\mpv\watch_later"
rd /s /q "%LocalAppData%\.IdentityService"
rd /s /q "%LocalAppData%\AWSToolkit"
rd /s /q "%LocalAppData%\AdvinstAnalytics"
rd /s /q "%LocalAppData%\CEF"
rd /s /q "%LocalAppData%\CefSharp"
rd /s /q "%LocalAppData%\Comms"
rd /s /q "%LocalAppData%\ConnectedDevicesPlatform"
rd /s /q "%LocalAppData%\CrashReportClient"
rd /s /q "%LocalAppData%\D3DSCache"
rd /s /q "%LocalAppData%\CrashDumps"
rd /s /q "%LocalAppData%\DBG"
rd /s /q "%LocalAppData%\Diagnostics"
rd /s /q "%LocalAppData%\EpicGamesLauncher\Saved\Crashes"
rd /s /q "%LocalAppData%\EpicGamesLauncher\Saved\Logs"
rd /s /q "%LocalAppData%\EpicGamesLauncher\Saved\webcache_4430\Cache"
rd /s /q "%LocalAppData%\EpicGamesLauncher\Saved\webcache_4430\Code Cache"
rd /s /q "%LocalAppData%\EpicGamesLauncher\Saved\webcache_4430\Service Worker\CacheStorage"
rd /s /q "%LocalAppData%\EpicGamesLauncher\Saved\webcache_4430\Service Worker\ScriptCache"
rd /s /q "%LocalAppData%\Epic Games"
rd /s /q "%LocalAppData%\Google\Chrome\User Data\Default\Cache"
rd /s /q "%LocalAppData%\Google\Chrome\User Data\Default\Code Cache"
rd /s /q "%LocalAppData%\Google\Chrome\User Data\Default\File System"
rd /s /q "%LocalAppData%\Google\Chrome\User Data\Default\GPUCache"
rd /s /q "%LocalAppData%\Google\Chrome\User Data\Default\Service Worker\CacheStorage"
rd /s /q "%LocalAppData%\Google\Chrome\User Data\Default\Service Worker\ScriptCache"
rd /s /q "%LocalAppData%\Links"
rd /s /q "%LocalAppData%\Microsoft\Edge\User Data\Default\Cache"
rd /s /q "%LocalAppData%\Microsoft\Edge\User Data\Default\Code Cache"
rd /s /q "%LocalAppData%\Microsoft\Edge\User Data\Default\File System"
rd /s /q "%LocalAppData%\Microsoft\Edge\User Data\Default\GPUCache"
rd /s /q "%LocalAppData%\NBTExplorer"
rd /s /q "%LocalAppData%\NVIDIA Corporation\NVIDIA GeForce Experience\CefCache\Cache"
rd /s /q "%LocalAppData%\NVIDIA Corporation\NVIDIA GeForce Experience\CefCache\Code Cache"
rd /s /q "%LocalAppData%\NVIDIA Corporation\NVIDIA GeForce Experience\CefCache\File System"
rd /s /q "%LocalAppData%\NVIDIA Corporation\NVIDIA GeForce Experience\CefCache\GPUCache"
rd /s /q "%LocalAppData%\NVIDIA Corporation\NVIDIA Share\CefCache\Cache"
rd /s /q "%LocalAppData%\NVIDIA Corporation\NVIDIA Share\CefCache\Code Cache"
rd /s /q "%LocalAppData%\NVIDIA Corporation\NVIDIA Share\CefCache\File System"
rd /s /q "%LocalAppData%\NVIDIA Corporation\NVIDIA Share\CefCache\GPUCache"
rd /s /q "%LocalAppData%\NVIDIA\GLCache"
rd /s /q "%LocalAppData%\NVIDIA\DXCache"
rd /s /q "%LocalAppData%\NuGet"
rd /s /q "%LocalAppData%\PlaceholderTileLogoFolder"
rd /s /q "%LocalAppData%\Publishers"
rd /s /q "%LocalAppData%\Qarmin\Czkawka\cache"
rd /s /q "%LocalAppData%\Roblox\Downloads"
rd /s /q "%LocalAppData%\Spotify\Browser\Cache"
rd /s /q "%LocalAppData%\Spotify\Browser\Code Cache"
rd /s /q "%LocalAppData%\Spotify\Browser\GPUCache"
rd /s /q "%LocalAppData%\Spotify\Data"
rd /s /q "%LocalAppData%\Spotify\Default\Cache"
rd /s /q "%LocalAppData%\Spotify\Default\Code Cache"
rd /s /q "%LocalAppData%\Spotify\Default\GPUCache"
rd /s /q "%LocalAppData%\StartIsBack"
rd /s /q "%LocalAppData%\Steam\htmlcache"
rd /s /q "%LocalAppData%\UnrealEngine"
rd /s /q "%LocalAppData%\Unreal Engine"
rd /s /q "%LocalAppData%\JetBrains\IdeaIC2025.1\caches"
rd /s /q "%LocalAppData%\JetBrains\IdeaIC2025.1\index"
rd /s /q "%LocalAppData%\JetBrains\IdeaIC2025.1\log"
rd /s /q "%LocalAppData%\kotlin"
rd /s /q "%LocalAppData%\UnrealEngineLauncher"
rd /s /q "%LocalAppData%\VirtualStore"
rd /s /q "%LocalAppData%\curseforge-updater"
rd /s /q "%LocalAppData%\cache"
rd /s /q "%LocalAppData%\ToastNotificationManagerCompat"
rd /s /q "%LocalAppData%\main.kts.compiled.cache"
rd /s /q "%LocalAppData%\Overwolf"
rd /s /q "%LocalAppData%\Paint.NET\AppCache"
rd /s /q "%LocalAppData%\PeerDistRepub"
rd /s /q "%LocalAppData%\pip"
rd /s /q "%LocalAppData%\Razer\RazerAppEngine\User Data\Logs"
rd /s /q "%LocalAppData%\Razer\RazerAppEngine\User Data\Default\Cache"
rd /s /q "%LocalAppData%\Razer\RazerAppEngine\User Data\Default\Code Cache"
rd /s /q "%LocalAppData%\npm-cache"
rd /s /q "%LocalAppData%\SquirrelTemp"
rd /s /q "%LocalAppData%\nzxt cam-updater\pending"
rd /s /q "%LocalAppData%\speech"
rd /s /q "%LocalAppData%\ImageMagick"
rd /s /q "%LocalAppData%\ImageGlass\ThumbnailsCache"
rd /s /q "%LocalAppData%\REDEngine"
rd /s /q "%LocalAppData%\Remnant2\.sentry-native"
rd /s /q "%LocalAppData%\Remnant2\Saved\Logs"
rd /s /q "%LocalAppData%\Stalker2\Saved\Crashes"
rd /s /q "%LocalAppData%\Stalker2\Saved\Backups"
rd /s /q "%LocalAppData%\Stalker2\Saved\Logs"
rd /s /q "%LocalAppData%\IdentityNexusIntegration"
rd /s /q "%LocalAppData%\gtk-4.0"
rd /s /q "%LocalAppData%\GameAnalytics"
rd /s /q "%LocalAppData%\anadius"
rd /s /q "%LocalAppData%\Microsoft\Terminal Server Client\Cache"
rd /s /q "%LocalAppData%\Microsoft\Edge\User Data\BrowserMetrics"
rd /s /q "%LocalAppData%\Roblox\logs"
rd /s /q "%LocalAppData%\Roblox\rbx-storage"
rd /s /q "%LocalAppData%\Roblox\tmp-capture-storage"
rd /s /q "%UserProfile%\.android"
rd /s /q "%UserProfile%\.arduinoIDE"
rd /s /q "%UserProfile%\.cache"
rd /s /q "%UserProfile%\.codetogether"
rd /s /q "%UserProfile%\.config"
rd /s /q "%UserProfile%\.dotnet"
rd /s /q "%UserProfile%\.matplotlib"
rd /s /q "%UserProfile%\.nuget"
rd /s /q "%UserProfile%\.templateengine"
rd /s /q "%UserProfile%\.gradle"
rd /s /q "%UserProfile%\.m2"
rd /s /q "%UserProfile%\UrbanVPN"
rd /s /q "%UserProfile%\ansel"
rd /s /q "%UserProfile%\.dbus-keyrings"
rd /s /q "%UserProfile%\Zomboid\Logs"
rd /s /q "%UserProfile%\Documents\MAXON"
rd /s /q "%UserProfile%\AppData\LocalLow\NVIDIA\PerDriverVersion\DXCache"
rd /s /q "%UserProfile%\AppData\LocalLow\Klei"
rd /s /q "%UserProfile%\AppData\LocalLow\miHoYo\Genshin Impact\Crashes"
rd /s /q "%UserProfile%\AppData\LocalLow\Intel\ShaderCache"
rd /s /q "%SystemDrive%\Program Files (x86)\Google\Update"
rd /s /q "%SystemDrive%\Program Files (x86)\Steam\logs"
rd /s /q "%SystemDrive%\Program Files (x86)\Steam\dumps"
rd /s /q "%SystemDrive%\Program Files (x86)\Steam\package"
rd /s /q "%SystemDrive%\Program Files (x86)\Steam\depotcache"
rd /s /q "%SystemDrive%\Program Files (x86)\Steam\appcache\librarycache"
rd /s /q "%SystemDrive%\Program Files (x86)\Steam\steamapps\shadercache"
rd /s /q "%SystemDrive%\Program Files (x86)\Steam\steamapps\common\Steamworks Shared\_CommonRedist"
rd /s /q "%SystemRoot%\Logs"
